# Generated by Django 3.2.11 on 2022-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='date',
            new_name='Date',
        ),
        migrations.AddField(
            model_name='articles',
            name='Anons',
            field=models.CharField(default='', max_length=250, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='articles',
            name='Full_info',
            field=models.TextField(default='', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='articles',
            name='Title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
